### ISSUE TITLE
Daemon starts AP on reboot, even if there is a valid wireless connection

### ISSUE THREAD

**Issue by arapulido** [CanonicalLtd/UCWifiConnect#25] opened 2017-04-17 14:11 UTC
Using wifi-connect rev 24.

Steps to reproduce:

 * I install Ubuntu Core 16 in a NUC with Wireless only (no ethernet)
 * I install required snaps, the wifi-connect snap, and connect interfaces
 * I get the error about the content interface that it is supposed to be "fixed" by connecting again or rebooting. I reboot.
 * After reboot, instead of putting the wireless in client mode, it seems like the daemon puts it in AP mode, locking me out

(As I haven't configured the AP yet, I cannot connect to this wireless AP, hence, cannot access to the web portal)

**Comment by knitzsche** [comment] 2017-04-17 14:26
just noting the mature daemon PR is not yet merged, and I've only ever tested in pi3. Be interesting to see if this occurs when the daemon is in place.

**Comment by knitzsche** [comment] 2017-04-19 13:57
I think this issue is valid. I think the problem is the default config of wifi-ap on install is UP. But, it should never be UP until we have SSIDs. So the daemon should set it to Down on first iteration of its loop (which will occur on boot and on daemon restart), then it can obtain ssids using network manager and then bring it up, or it will simply connect to an external ap if there has already been such an external connection. 

For what it's worth, if you run this command before I fix this, it should just work: sudo wifi-connect.wifi-ap -ap-off

**Comment by arapulido** [comment] 2017-04-20 13:59
The workaround doesn't work for me, as I get the content interface issue

**Comment by knitzsche** [comment] 2017-04-20 14:12
Yes, I discovered that if you have never connected to external wifi via wifi-connect.netman command, it fails from the GUI. Try running that, then things should work

**Comment by knitzsche** [comment] 2017-04-28 14:49
This is fixed with PR https://github.com/CanonicalLtd/UCWifiConnect/pull/27.

**Closed by knitzsche** 2017-04-28 14:49 UTC
Labels: bug
